# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: registry-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: registry
#   template:
#     metadata:
#       labels:
#         app: registry
#     spec:
#       containers:
#       - name: registry-container
#         image: registry:2.7.1
#         ports:
#         - containerPort: 5000
#         volumeMounts:
#         - name: registry-storage
#           mountPath: /var/lib/registry
#         livenessProbe:
#           tcpSocket:
#             port: 5000
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         readinessProbe:
#           tcpSocket:
#             port: 5000
#           initialDelaySeconds: 10
#           periodSeconds: 10
#       volumes:
#       - name: registry-storage
#         persistentVolumeClaim:
#           claimName: registry-pvc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: registry-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Gi
      
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: registry-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: registry
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 5000
